{% set name = "gocryptfs" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rfjakob/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f972d95d8e295e177cb0ab20598d7a52d77c1b982c208bfc9417bde8726d80ae

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gocryptfs -h

about:
  home: https://github.com/rfjakob/gocryptfs
  summary: 'Encrypted overlay filesystem written in Go'
  description: |
    gocryptfs is built on top the excellent go-fuse FUSE library.
    This project was inspired by EncFS and strives to fix its security issues while providing good performance.
    For details on the security of gocryptfs see the Security design document.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - license-files/
  doc_url: nuetzlich.net/gocryptfs/
  dev_url: https://github.com/rfjakob/gocryptfs

extra:
  recipe-maintainers:
    - vinisalazar
